-- Generated by Mocodo 4.1.1

CREATE TABLE ATHLETE (
  PRIMARY KEY (id_athlete),
  id_athlete     INT(4) NOT NULL AUTO_INCREMENT,
  nom_athlete    VARCHAR(255),
  prenom_athlete VARCHAR(255),
  id_pays        INT(4) NOT NULL,
  id_genre       INT(4) NOT NULL
);

CREATE TABLE EPREUVE (
  PRIMARY KEY (id_epreuve),
  id_epreuve    INT(4) NOT NULL AUTO_INCREMENT,
  nom_epreuve   VARCHAR(255),
  date_epreuve  DATE,
  heure_epreuve TIME,
  id_lieu       INT(4) NOT NULL,
  id_sport      INT(4) NOT NULL
);

CREATE TABLE GENRE (
  PRIMARY KEY (id_genre),
  id_genre  INT(4) NOT NULL AUTO_INCREMENT,
  nom_genre VARCHAR(255)
);

CREATE TABLE LIEU (
  PRIMARY KEY (id_lieu),
  id_lieu      INT(4) NOT NULL AUTO_INCREMENT,
  nom_lieu     VARCHAR(255),
  adresse_lieu VARCHAR(255),
  cp_lieu      VARCHAR(5),
  ville_lieu   VARCHAR(255)
);

CREATE TABLE PARTICIPER (
  PRIMARY KEY (id_athlete, id_epreuve),
  id_athlete INT(4) NOT NULL,
  id_epreuve INT(4) NOT NULL,
  resultat   VARCHAR(100)
);

CREATE TABLE PAYS (
  PRIMARY KEY (id_pays),
  id_pays  INT(4) NOT NULL AUTO_INCREMENT,
  nom_pays VARCHAR(255)
);

CREATE TABLE SPORT (
  PRIMARY KEY (id_sport),
  id_sport  INT(4) NOT NULL AUTO_INCREMENT,
  nom_sport VARCHAR(255)
);

CREATE TABLE UTILISATEUR (
  PRIMARY KEY (id_utilisateur),
  id_utilisateur     INT(4) NOT NULL AUTO_INCREMENT,
  nom_utilisateur    VARCHAR(255),
  prenom_utilisateur VARCHAR(255),
  login              VARCHAR(255),
  password                VARCHAR(255)
);

ALTER TABLE ATHLETE ADD FOREIGN KEY (id_genre) REFERENCES GENRE (id_genre);
ALTER TABLE ATHLETE ADD FOREIGN KEY (id_pays) REFERENCES PAYS (id_pays);

ALTER TABLE EPREUVE ADD FOREIGN KEY (id_sport) REFERENCES SPORT (id_sport);
ALTER TABLE EPREUVE ADD FOREIGN KEY (id_lieu) REFERENCES LIEU (id_lieu);

ALTER TABLE PARTICIPER ADD FOREIGN KEY (id_epreuve) REFERENCES EPREUVE (id_epreuve);
ALTER TABLE PARTICIPER ADD FOREIGN KEY (id_athlete) REFERENCES ATHLETE (id_athlete);
